### ISSUE TITLE
nvprof was split into two pieces for 11.8

### ISSUE THREAD

**Issue by mmohrhard** [negativo17/cuda-nvprof#1]
I'm filing this issue here as this relates to files that moved from the nvprof package to a new package in 11.8.

With CUDA 11.8 it seems that Nvidia has split out the profiler headers from the nvprof package. As far as I can see this new package is currently not included in the repo.

The new package with the corresponding content:

https://developer.download.nvidia.com/compute/cuda/redist/cuda_profiler_api/linux-x86_64/

```
tar tf cuda_profiler_api-linux-x86_64-11.8.86-archive.tar.xz 
cuda_profiler_api-linux-x86_64-11.8.86-archive/
cuda_profiler_api-linux-x86_64-11.8.86-archive/include/
cuda_profiler_api-linux-x86_64-11.8.86-archive/include/cudaProfiler.h
cuda_profiler_api-linux-x86_64-11.8.86-archive/include/cuda_profiler_api.h
cuda_profiler_api-linux-x86_64-11.8.86-archive/LICENSE
```

The old 11.7 nvprof package with the two include files

```
tar tf cuda_nvprof-linux-x86_64-11.7.101-archive.tar.xz  | grep include
cuda_nvprof-linux-x86_64-11.7.101-archive/include/
cuda_nvprof-linux-x86_64-11.7.101-archive/include/cudaProfiler.h
cuda_nvprof-linux-x86_64-11.7.101-archive/include/cuda_profiler_api.h
```

Would it be possible to package the cuda_profile_api as part of the repo?

**Comment by scaronni** [comment]
Right, this was actually in my todo list but I forgot, among the various things.

![image](https://user-images.githubusercontent.com/1983966/208868621-18ecbd12-3410-41d9-9217-bc61901adfc6.png)

It will be online in a few hours.

Thanks for reporting!

**Comment by scaronni** [comment]
Added both the 11.8 and 12.0 builds. The package with the two headers is called `cuda-profiler-devel`. Don't know why they split it considering it's already deprecated like `nvprof`.

**Comment by mmohrhard** [comment]
Thanks for the quick fix.

We only noticed it because pycuda still depends on these headers.
